import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EBF3FA",
  },
  banner: {
    height: 130,
    backgroundColor: "#1B4F8A",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  avatarWrapper: {
    position: "absolute",
    bottom: -36,
    alignSelf: "center",
    borderRadius: 50,
    borderWidth: 3,
    borderColor: "#EBF3FA",
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 26,
  },
  content: {
    marginTop: 44,
    paddingHorizontal: 16,
    paddingBottom: 32,
    alignItems: "center",
  },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#1B4F8A",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 16,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  editBtnText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  userName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1B3A5C",
    marginBottom: 4,
  },
  userCourse: {
    fontSize: 14,
    color: "#6B8BA4",
    marginBottom: 2,
  },
  userSemester: {
    fontSize: 13,
    color: "#9BB5C8",
    marginBottom: 16,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 32,
    gap: 32,
    marginBottom: 16,
    alignSelf: "stretch",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  statItem: {
    alignItems: "center",
    gap: 2,
  },
  statNumber: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B3A5C",
  },
  statLabel: {
    fontSize: 12,
    color: "#6B8BA4",
  },
  statDivider: {
    width: 1,
    height: 32,
    backgroundColor: "#D6E8F5",
  },
  connectBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#1B4F8A",
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 8,
    marginBottom: 24,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  connectBtnActive: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#1B4F8A",
  },
  connectBtnText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  connectBtnTextActive: {
    color: "#1B4F8A",
  },
  section: {
    alignSelf: "stretch",
    gap: 10,
  },
  infoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    gap: 6,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#9BB5C8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoValueRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  infoValue: {
    fontSize: 14,
    color: "#2C3E50",
    flex: 1,
  },
  postsContainer: {
    width: "100%",
    marginTop: 24,
    gap: 12,
  },
  postsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B3A5C",
    marginBottom: 8,
  },
  skillsSection: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  skillsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  skillsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1B3A5C",
  },
  editSkillsButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  editSkillsText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1B4F8A",
  },
  skillsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  skillTag: {
    backgroundColor: "#E8F1F8",
    borderWidth: 1,
    borderColor: "#D4E4F2",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  skillText: {
    color: "#1B4F8A",
    fontSize: 13,
    fontWeight: "600",
  },
  skillsTopBar: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  skillInput: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#DCE7F2",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    color: "#1B3A5C",
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "#E8F1F8",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
});

export default styles;
